---
version: '3'
services:
    common: &common
        image: hashicorp/terraform:1.7
        working_dir: /workdir
        environment:
          - AWS_ACCESS_KEY_ID
          - AWS_REGION=ap-southeast-2
          - AWS_SECRET_ACCESS_KEY
          - AWS_SESSION_TOKEN
          - ENV
          - TF_LOG
        volumes:
          - ${HOME}/.aws:/root/.aws:ro
          - ${PWD}:/workdir
        network_mode: bridge

    tf-action:
        <<: *common
        command: >
            $COMMAND